### ISSUE TITLE
the meaning of 'label' in CSV files

### ISSUE THREAD

**Issue by EverythingWillBeOk1** [network-traffic/AppSniffer#1]
May I ask if you can release the code for generating CSV files from pickle files? I don't quite understand the meaning of 'label' in CSV files.

**Comment by sanghakoh** [comment]
Label is an index of a list of mobile apps.

(AppSniffer: Towards Robust Mobile App Fingerprinting Against VPN, page 11, Table 10: List of Mobile Apps. https://dl.acm.org/doi/pdf/10.1145/3543507.3583473)

![applist](https://github.com/user-attachments/assets/61802d44-eff5-4538-b37e-b757f0471296)

I will upload the code that generates CSV files from pickle files.

**Comment by EverythingWillBeOk1** [comment]
I understand, thank you very much

**Comment by sanghakoh** [comment]
I will first share my small code here that converts a pickle file to a CSV file. It’s not clean code, but I hope it will be helpful. I plan to clean it up and then upload it to this repository.
[pickle_to_csv_code.zip](https://github.com/user-attachments/files/18008837/pickle_to_csv_code.zip)

**Comment by EverythingWillBeOk1** [comment]
thanks

**Comment by ljblob** [comment]
> I will first share my small code here that converts a pickle file to a CSV file. It’s not clean code, but I hope it will be helpful. I plan to clean it up and then upload it to this repository. [pickle_to_csv_code.zip](https://github.com/user-attachments/files/18008837/pickle_to_csv_code.zip)

Hi, thanks for your sharing! I have a couple of questions about the dataset.

1. Do the labels in the normal, nordVPN, SuperVPN, and Surfshark datasets refer to the same APP? For example, Label 0 in these four datasets is ''sg.bigo.live''. 
2. What does the range of 0-100 represent? I found 'Dataset_generation/appList_us.txt' is different from 'normal100_final_list.txt'.

**Comment by sanghakoh** [comment]
Thank you for your interest in my work, and I apologize for any confusion caused by my code.

Here are my answers to your questions:
1. According to my code, all dataset labels (e.g., for NordVPN, TurboVPN) remain the same based on the script "pickle_to_csv.py."

![Image](https://github.com/user-attachments/assets/c0f375d7-c5ea-4388-b4c1-b04a929f3898)

This code assigns index numbers to app names using the line number in the text file "normal100_final_list.txt," ensuring that label numbers remain consistent across datasets. However, I initially tested with 100 apps but later extended the dataset to 150 apps. 

I have attached the final 150 app text file ("normal100_final_list_1to150.txt"). You can determine an app’s label by using (line number - 1) in this file. If you need more precise label names, I recommend downloading the pickle format dataset from my GitHub repository. The pickle files includes specific app names for each traffic data sample. (https://github.com/network-traffic/AppSniffer/tree/main/datasets/Pickle%20files)

[normal100_final_list_1to150.txt](https://github.com/user-attachments/files/18784886/normal100_final_list_1to150.txt)

2. As mentioned above, labels 0-100 correspond to specific app names. During traffic collection and evaluation, I tested various apps, including some that were not mentioned in the paper. The files "appList_us.txt" and "normal100_final_list.txt" were part of an earlier version of my app list. Please disregard them and use the attached text file as the final version for my experiments.

**Comment by ljblob** [comment]
Thank you for your time and clarification！

I encountered an error while trying to load a .pickle file using the flowprint library. 
Does the error message indicates that a incorrect installation of the flowprint library？
```plaintext
Traceback (most recent call last):
  File "/home/wislab/AppSniffer/datasets/pickle_to_csv_code/pickle_to_csv.py", line 386, in <module>
    main2(dataset, cv, 5000)
  File "/home/wislab/AppSniffer/datasets/pickle_to_csv_code/pickle_to_csv.py", line 311, in main2
    X_, y_ = preprocessor.load(file)
  File "/home/wislab/anaconda3/envs/autogluon/lib/python3.8/site-packages/flowprint/preprocessor.py", line 156, in load
    return pickle.load(infile)
ModuleNotFoundError: No module named 'flows'

**Comment by sanghakoh** [comment]
No, you do not have to download and install all the files of the flowprint to use the module 'flows.'

As I mentioned in the readme.md, you should download "flow.py" (which included "Flow" class object datastructure) in FlowPrint project and include the file with my code. 

[https://github.com/Thijsvanede/FlowPrint/blob/master/flowprint/flows.py](https://github.com/Thijsvanede/FlowPrint/blob/master/flowprint/flows.py)

<Below is a captured image of Readme file in AppSniffer/datasets/Pickle files>

![Image](https://github.com/user-attachments/assets/dd946fc1-d94d-4bfa-b244-22a791d695e8)

**Comment by ljblob** [comment]
Cheers! Got the code working!
